"""initial

Revision ID: aedba0959d27
Revises:
Create Date: 2023-04-12 20:52:56.704781

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aedba0959d27"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("uid"),
    )
    op.create_table(
        "user",
        sa.Column("login", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("birth_date", sa.DateTime(), nullable=True),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_table(
        "user_history",
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("device_type", sa.String(), nullable=True),
        sa.Column("auth_datetime", sa.DateTime(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_history")
    op.drop_table("user")
    op.drop_table("role")
    # ### end Alembic commands ###
