"""jwt

Revision ID: ce99031c7eb0
Revises: 3eb1635d3d58
Create Date: 2023-04-20 07:38:59.473684

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce99031c7eb0"
down_revision = "3eb1635d3d58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jwt_store",
        sa.Column("jwt_id", sa.String(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_unique_constraint(None, "login_history", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "login_history", type_="unique")
    op.drop_table("jwt_store")
    # ### end Alembic commands ###
